### ISSUE TITLE
liblz4-java doesn't clean temporary files

### ISSUE THREAD

**Issue by maver1ck** [lz4/lz4-java#102]
Library creates files in /tmp/liblz4-java*.so path and leaves them at program finish.
Is is possible to clean them up ?

**Comment by odaira** [comment]
lz4-java is supposed to clean it up at program exit, unless your JVM crashes: https://github.com/lz4/lz4-java/blob/master/src/java/net/jpountz/util/Native.java#L124. What is your platform?

**Comment by odaira** [comment]
Do you still see this problem?

**Comment by odaira** [comment]
I will close this issue unless anyone has any objection.
