### ISSUE TITLE
Automated snapshot build?

### ISSUE THREAD

**Issue by danielfree** [lz4/lz4-java#107]
Is it possible to add automated building pipeline for snapshot release? Maybe [travis-ci](https://travis-ci.org) can help. Yet we still need to build different lz4 libs (win&linux&mac), and travis-ci only supports ubuntu & osx, any suggestion?

**Comment by odaira** [comment]
Yes, I am thinking about it.  For automated snapshot releases, I don't think we need to build JNI bindings.  We can just bundle the pre-build bindings in src/resources/.
