### ISSUE TITLE
J2ME compatibility

### ISSUE THREAD

**Issue by lucianocoan** [lz4/lz4-java#114]
Is there plans to make a version compatible with j2me?
Thanks

**Comment by odaira** [comment]
Hi,
Unfortunately, I am not familiar with J2ME. What is needed to make it J2ME compatible?

**Comment by lucianocoan** [comment]
Hi, I´m a newbie on it. What I´ve checked until now is that the J2ME CLDC does not have java.util.Arrays (for example). There are a lot of others libs that J2ME does not have.
Another examplo: This line:
final Class<?> c = loader.loadClass(cls);
Is invalid...
This are few examples with errors taken from code when I try to import it on my J2ME project.

Thanks!

**Comment by odaira** [comment]
Looks like it will require major rework to make it compatible with J2ME.  I don't have a plan to work on it, but if you or somebody else submit a PR, I'll give thought to it.
