### ISSUE TITLE
Unable to decompress  using lz4net

### ISSUE THREAD

**Issue by rsrini83** [lz4/lz4-java#115]
We are compressing the stream using java library. More precisely using LZ4BlockOutputStream. However we are unable to decompress these in C# using lz4net.  

Do we need to take care of any thing specifically to support this ?

**Comment by odaira** [comment]
LZ4BlockOutputStream is old and uses its own format, while LZ4FrameOutputStream is implemented in lz4-java 1.4.0 and is compatible with the LZ4 Frame format.  I am not sure what format lz4net is using, but can you try LZ4FrameOutputStream?

**Comment by rsrini83** [comment]
Thanks odaira for the response.

i'm using 1.3.0 from maven repo and I couldn't find 1.4.0 version in maven repo. Where can i find the latest version.

**Comment by odaira** [comment]
We have moved our maven repo: http://repo1.maven.org/maven2/org/lz4/lz4-java/1.4.0/
