### ISSUE TITLE
Clarification on Apache license

### ISSUE THREAD

**Issue by omkreddy** [lz4/lz4-java#121]
Some of the source files are all under GPLv2.

lz4-java-1.4.0/src/lz4/examples/Makefile
lz4-java-1.4.0/src/lz4/programs/lz4cli.c
lz4-java-1.4.0/lz4-java-1.4.0/src/lz4/programs/lz4io.c
lz4-java-1.4.0/lz4-java-1.4.0/src/lz4/programs/lz4io.h
lz4-java-1.4.0/lz4-java-1.4.0/src/lz4/programs/Makefile
lz4-java-1.4.0/lz4-java-1.4.0/src/lz4/programs/bench.c
lz4-java-1.4.0/lz4-java-1.4.0/src/lz4/programs/datagen.c
lz4-java-1.4.0/lz4-java-1.4.0/src/lz4/programs/fullbench.c
...
...

Will using lz4-java-1.4.jar violates GPL license?

**Comment by odaira** [comment]
In my understanding, no.

lz4-java is linked with only the source files under the src/lz4/lib directory, which are all BSD-licensed, which is in turn compatible with the Apache License.  All the other files under src/lz4 were just copied from the lz4 upstream, but they were not referred to or linked by lz4-java.

FYI, from lz4-java 1.5, the src/lz4 directory will be managed as a git submodule and will no longer be even part of the lz4-java distribution.

**Comment by omkreddy** [comment]
@odaira  Thanks for the clarification.
