### ISSUE TITLE
Java 9 compatibility

### ISSUE THREAD

**Issue by obowden** [lz4/lz4-java#122]
Hi, 

I've just run the dependency checking tool jdeps on the lz4-java-1.4.1.jar file and it's flagged a usage of the sun.misc.Unsafe package that is not supported in Java 9:

digraph "lz4-java-1.4.1.jar" {
   "net.jpountz.util.UnsafeUtils"                     -> "sun.misc.Unsafe (JDK internal API (rt.jar))";
}

Has this been tested against Java 9, or are there plans to release a Java 9 compatible version?

Thanks

**Comment by mkozioro** [comment]
Hi @obowden.
If I remember good, LZ4 can use different kinds of compressors and decompressors. One safe, one using unsafe and one using JNI bindings. Maybe just try safe one.

**Comment by obowden** [comment]
Thanks for getting back to me.  I'll check that out.

**Comment by odaira** [comment]
lz4-java runs with Java 9 or later at least for the moment. OpenJDK still supports sun.misc.Unsafe. I will work on it once OpenJDK stops supporting sun.misc.Unsafe. Let me know if you find any other JVM that dropped sun.misc.Unsafe.

Building lz4-java with Java 9 caused some errors, so I have updated build.xml and ivy.xml to fix them.
