### ISSUE TITLE
Delete of native lib doesn't work on Windows

### ISSUE THREAD

**Issue by broneill** [lz4/lz4-java#132]
This is a duplicate of issue #102, which was closed without actually being fixed. When loading a native library on Windows, the file is locked and cannot be deleted. Attempting to use the "delete on exit" feature doesn't actually work, because the delete attempt occurs before the native library is unloaded.

**Comment by odaira** [comment]
Fixed by 08b3bff3491eafd5238c5adf79113e56f6821e82.
