### ISSUE TITLE
LZ4FrameInputStream should read InputStream lazily

### ISSUE THREAD

**Issue by bjmi** [lz4/lz4-java#146]
Creating a new `LZ4FrameInputStream` instance already reads the underlying `InputStream` by calling [nextFrameInfo()](https://github.com/lz4/lz4-java/blob/1.6.0/src/java/net/jpountz/lz4/LZ4FrameInputStream.java#L86).
This call should be deferred until an actual read(...) is performed i.e. separate instance creation and utilization.

Advantages
* If input is never read or used no resources or handles would be allocated.
* My use-case: underlying `InputStream` is not ready when creating LZ4FrameInputStream but actually is when used.

**Comment by odaira** [comment]
Fixed by 5e2357339ff4b0dc7eb0e5a21a500d0ca5508594.  Instance creation of `LZ4FrameInputStream` becomes 300x faster.  Thanks for your suggestion!
