### ISSUE TITLE
Release jar-no-jni artifact

### ISSUE THREAD

**Issue by EvelynEZ** [lz4/lz4-java#148]
Is it possible to release a jar-no-jni build to maven artifactory? I am trying to avoid using any of the native (jni) instance and want a java-only library.

**Comment by odaira** [comment]
OK, let me try....  I'm thinking of `lz4-pure-java` as an artifact ID. Out of curiosity, in what use case do you need a java-only version?

**Comment by EvelynEZ** [comment]
That would be awesome! Thanks.
My project is pure java and I try to avoid native library as I find it really hard to debug.
Compared to making sure I do not accidentally use any of the native instance, it would be much better if there is a pure java build for this library.

**Comment by odaira** [comment]
Committed necessary changes. Will release a java-only version from the next release.

**Comment by EvelynEZ** [comment]
Thank you very much!
