### ISSUE TITLE
Error creating android project

### ISSUE THREAD

**Issue by maffbm** [lz4/lz4-java#149]
Hi, I don;t know what LZ4 is or jpounts, and I've not referenced either in my project, but I'm trying to create a signed bundle at the moment in Android Studio and getting the following error:
e: java.io.IOException: net.jpountz.lz4.LZ4Exception: Malformed input at 15

Any ideas?

Thanks

**Comment by odaira** [comment]
LZ4 is the name of a data compression algorithm and its format. `net.jpountz.lz4.LZ4Exception: Malformed input at 15` means that something is trying to decompress data but the data format is not correct as LZ4. I would investigate what it is trying to decompress and check whether the data is really in the LZ4 format or not.

**Comment by maffbm** [comment]
Thank you, it's odd because all I did was add 3 lines of code. I'm not compressing anything

**Comment by odaira** [comment]
Would you still need any help?

**Comment by odaira** [comment]
I'll close this.  Feel free to reopen it if you need more help.
