### ISSUE TITLE
Please apply Apache 2.0 license properly

### ISSUE THREAD

**Issue by enepomnyaschih** [lz4/lz4-java#162]
Could you please properly apply Apache 2.0 license to your module as described in http://www.apache.org/licenses/LICENSE-2.0? It can be achieved either by including the offered header to all source code files or by including a NOTICE file with the same text. Currently your source code doesn’t contain any copyright clauses, and they are necessary.

**Comment by odaira** [comment]
Thanks for the heads-up!  Fixed by 55bede61a72803574c638a1ef1a70eadc6cefa6e.

**Comment by enepomnyaschih** [comment]
Thank you!
