### ISSUE TITLE
LZ4SafeDecompressor requires length

### ISSUE THREAD

**Issue by sksamuel** [lz4/lz4-java#179]
Hi,

The docs make it seem like decompressed length is not required for LZ4SafeDecompressor but it requires it.
Is the solution just make a huge array that you know will be big enough ?
If so, what's the best size to choose?

**Comment by odaira** [comment]
> Is the solution just make a huge array that you know will be big enough ?

Correct, but LZ4SafeDecompressor/LZ4FastDecomparessor are low-level APIs, and users will usually know the decompressed size (e.g. when they compress a fixed-sized buffer) or will store the decompressed size somewhere.

> If so, what's the best size to choose?

Unfortunately, there is no known "best size", and the maximum compression ratio of lz4 is 255, which would be too large.

If you need to compress/decompress unknown-sized data, it would be a good indication that you should use the streaming-oriented APIs, i.e. LZ4FrameInputStream/LZ4FrameOutputStream.  If you really need block-oriented APIs, LZ4CompressorWithLength/LZ4DecompressorWithLength are also provided, for convenience.

See also #26 and #88.

**Comment by sksamuel** [comment]
The stream orientated APIs seem great.

**Comment by odaira** [comment]
Would you need more help?

**Comment by sksamuel** [comment]
I haven't tried your suggestion yet, but I'm sure it will work.
We can close this.
Thanks for your help :)
