### ISSUE TITLE
Native Build Quarkus

### ISSUE THREAD

**Issue by SereiaMaster** [lz4/lz4-java#191]
I have some problems with native build with Quarkus

`"java.lang.AssertionError: java.lang.ClassNotFoundException: net.jpountz.lz4.LZ4JavaSafeCompressor`

I cant find any generated class from costructor instances

**Comment by liuxgo** [comment]
@SereiaMaster Hi, did you find a solution with this issue?

**Comment by SereiaMaster** [comment]
Yes, I have been used a LZ4Factory.fastestInstance(). That error not occours anymore.
