### ISSUE TITLE
lz4 streaming format 1.4

### ISSUE THREAD

**Issue by jdamick** [lz4/lz4-java#21]
It doesn't look like the LZ4BlockOutputStream / LZ4BlockInputStream support the streaming format described here: http://fastcompression.blogspot.com/2013/04/lz4-streaming-format-final.html

Is this on the roadmap or is there a different set of streams I need to use for compatibility?

thanks

**Comment by phraktle** [comment]
+1 for this.

Btw, there's a basic implementation already available in Apache Kafka, see:
https://github.com/apache/kafka/tree/0.8.2/clients/src/main/java/org/apache/kafka/common/message

**Comment by drcrallen** [comment]
It seems to have moved in trunk:
https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/record/KafkaLZ4BlockOutputStream.java

Also, it says it supports "A partial implementation of the v1.4.1 LZ4 Frame format." rather than full 1.5 support, which is concerning.

**Comment by dpkp** [comment]
The Kafka implementation is a bit broken, but I've done some work to fix it and update for 1.5.1 lz4 frame spec. See https://cwiki.apache.org/confluence/display/KAFKA/KIP-57+-+Interoperable+LZ4+Framing and  https://github.com/apache/kafka/pull/1212

**Comment by odaira** [comment]
Thanks all, and the LZ4 Frame format has been supported by lz4-java since 1.4.0.
