### ISSUE TITLE
How can i decompress value, if i don't know maxDestLen?

### ISSUE THREAD

**Issue by i-davydov** [lz4/lz4-java#26]
Hello.

How can i decompress value, if i don't know maxDestLen?

**Comment by eyalroth** [comment]
> I am closing this one since this is not really an issue

Seriously? this just makes the API more cumbersome and adds work to the user. Why not simply add a header to the compressed data with the decompressed length? sounds to me like an easy way of encapsulating this logic from the user.

**Comment by kaushalhakani** [comment]
> encode the original length before the compressed bytes to be able to know the original length at decompression time

This should be provided as one of the implementations rather than asking most users to implement it. If you would like it I can contribute that piece of code.

**Comment by odaira** [comment]
This functionality was implemented by LZ4CompressorWithLength and LZ4DecompressorWithLength (#119) in the master branch.  It will be included in the next release.

**Comment by gerritjvv** [comment]
Could you update the README.md so that LZ4CompressorWithLength is known while reading the readme? It took me quite a while to actually find that this class exists.
thanks!.
