### ISSUE TITLE
Android version 

### ISSUE THREAD

**Issue by scottyab** [lz4/lz4-java#29]
lz4-1.2.0.jar is incompatible with Android as in contains native libraries that will not run on the device. As a quick hack I've manually removed the following from the jar linux/amd64/liblz4-java.so,  linux/i386/liblz4-java.so, win32/amd64/liblz4-java.and it so but it would be great to have a Android specific version with separate ARM and x86 native libraries.  Great lib thanks for the hard work.

**Comment by odaira** [comment]
Would you still need any help for this?  It's easy to create a new target in build.xml that generates a jar without the JNI libraries.  I'll add it if you want it.

**Comment by lukasblu** [comment]
@odaira having such a target in the official build.xml would be great! Thx already :-)

**Comment by scottyab** [comment]
Hey @odaira thanks for the repsonse, lz4 isn't something I've used in the past few years it was only a requirement at a previous job so atm it's not something I'm personally looking for. But I think it would be valuable. All the best.

**Comment by odaira** [comment]
I have added a new target "jar-no-jni" with 8369daf708b4905b1d425d252e426304f40b0039.  Please reopen this issue if you need further support for Android.
