### ISSUE TITLE
JNI Windows 

### ISSUE THREAD

**Issue by mdhsl** [lz4/lz4-java#34]
Hi,

I am trying to use LZ4 as native on WIN 7 32/64bits but after compiling the project, I've got an UnsatisfiedLinkError. 

The file generated is an *.so file under win32/x86/

This file should not be a *.dll file? Anyway I have already read a post which seems relate the same problem but i did not see any solution for that. How i can get this working?

Thx

**Comment by odaira** [comment]
Do you still need any help?  I don't have a build environment for Windows, so I am not sure if I can help you, though.

**Comment by odaira** [comment]
Let me close this issue, but feel free to reopen it if you need help on this.
