### ISSUE TITLE
Possible overallocation in LZ4BlockInputStream

### ISSUE THREAD

**Issue by mtopolnik** [lz4/lz4-java#70]
LZ4BlockInputStream, line 188:

```
    case COMPRESSION_METHOD_LZ4:
      if (compressedBuffer.length < originalLen) {
        compressedBuffer = new byte[Math.max(compressedLen, compressedBuffer.length * 3 / 2)];
      }
```

I believe that comparing compresed buffer length to `originalLen` is wrong; it should be compared to `compressedLength`. This isn't severe, but results in an unnecessary amount of memory being allocated for the compressed buffer.

**Comment by odaira** [comment]
Fixed by c8f4371931a356036a201f01475df99e4be7726c. Thanks!
