### ISSUE TITLE
Update to latest upstream lz4 and release new lz4-java version?

### ISSUE THREAD

**Issue by Valloric** [lz4/lz4-java#74]
Last official release is 1.3.0 from Nov 26, 2014. Any chance of updating to latest lz4 and pushing out a new official release?

**Comment by puntogil** [comment]
Hi
was released also xxHash v0.5.0 any plan for use this newer release?
Thanks in advance

**Comment by cavanaug** [comment]
This is getting bad.   The default reference C implementation lz4 (r128) available in Ubuntu is incompatible with lz4-java.

**Comment by odaira** [comment]
Released 1.5.0, based on the latest lz4 1.8.3.
