### ISSUE TITLE
Are factory, compressor and decompressor thread-safe

### ISSUE THREAD

**Issue by tenstriker** [lz4/lz4-java#82]
Hi, thanks for the library. I was wondering if following instances are thread-safe and can be declared as static or as class level and can be called from multiple threads safely.

`val factory = LZ4Factory.fastestInstance()
val compressor = factory.fastCompressor()
  val decompressor = factory.fastDecompressor()
  val decompressorSafe = factory.safeDecompressor()`

**Comment by odaira** [comment]
Hi, they are all thread-safe.
