### ISSUE TITLE
Source code for Unsafe* XXHash?

### ISSUE THREAD

**Issue by velvia** [lz4/lz4-java#94]
Hi guys,

Maybe this is a dumb question but where can I find the Java source code for the Unsafe XXHash routines?  They are loaded dynamically at runtime but I'm trying to figure out where they come from.

For a certain high speed implementation I'm wondering if it is possible to access the hashing function directly without needing to copy data to a byte array.   If not I'd like to have a look at the source code.

thanks

**Comment by odaira** [comment]
They are generated at build time from templates. You can find the templates at src/build/source_templates.

**Comment by odaira** [comment]
Can I close this issue?  Did you find the source code?

**Comment by velvia** [comment]
Will close, thanks.
