### ISSUE TITLE
Restarting the development

### ISSUE THREAD

**Issue by odaira** [lz4/lz4-java#96]
Hi, @lz4/lz4_java 
How are we going to restart the development?  Who is to review the PRs?

Thanks,

**Comment by Cyan4973** [comment]
Do you have any public email we could use to discuss this topic ?
Alternatively, if you wish to keep it private, we can initiate the discussion through this interface : 
http://www.emailmeform.com/builder/form/a70egol6fyVf15zd46jY88

**Comment by odaira** [comment]
I have updated my profile to show my public email.

**Comment by Cyan4973** [comment]
@odaira is now officially maintainer of lz4-java
